package com.greenwood.school.ui.feature.payroll

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Tab
import androidx.compose.material3.TabRow
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewModelScope
import com.greenwood.school.core.common.DocumentOpener
import com.greenwood.school.core.common.Formatters
import com.greenwood.school.core.network.ApiResult
import com.greenwood.school.core.network.getOrNull
import com.greenwood.school.data.remote.dto.PayrollDashboardDto
import com.greenwood.school.data.remote.dto.PayrollRunDto
import com.greenwood.school.data.remote.dto.SalaryStructureDto
import com.greenwood.school.domain.repository.PayrollRepository
import com.greenwood.school.ui.common.PagedListState
import com.greenwood.school.ui.common.PagedLoader
import com.greenwood.school.ui.common.UiMessage
import com.greenwood.school.ui.components.AppCard
import com.greenwood.school.ui.components.AppTopBar
import com.greenwood.school.ui.components.EmptyView
import com.greenwood.school.ui.components.EntityRowCard
import com.greenwood.school.ui.components.ErrorView
import com.greenwood.school.ui.components.FullScreenLoader
import com.greenwood.school.ui.components.LoadMoreFooter
import com.greenwood.school.ui.components.StatusChip
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.time.LocalDate
import javax.inject.Inject

/**
 * Payroll: this month's runs and the salary structures behind them.
 *
 * Salary slips are PDFs generated by the backend — the app downloads and opens
 * them rather than re-rendering the layout, so the printed slip is byte-identical
 * to the one the web app produces.
 */
@Composable
fun PayrollScreen(
    onBack: (() -> Unit)? = null,
    viewModel: PayrollViewModel = hiltViewModel(),
) {
    val state by viewModel.state.collectAsStateWithLifecycle()
    val runs by viewModel.runs.collectAsStateWithLifecycle()
    var tab by remember { mutableIntStateOf(0) }
    val snackbarHostState = remember { SnackbarHostState() }

    LaunchedEffect(state.message?.id) {
        state.message?.let {
            snackbarHostState.showSnackbar(it.text)
            viewModel.consumeMessage()
        }
    }

    Scaffold(
        topBar = { AppTopBar(title = "Payroll", onBack = onBack) },
        snackbarHost = { SnackbarHost(snackbarHostState) },
    ) { padding ->
        Column(Modifier.fillMaxSize().padding(padding)) {
            state.dashboard?.let { DashboardStrip(it) }

            TabRow(selectedTabIndex = tab) {
                listOf("Runs", "Structures").forEachIndexed { index, label ->
                    Tab(
                        selected = tab == index,
                        onClick = {
                            tab = index
                            if (index == 1) viewModel.loadStructures()
                        },
                        text = { Text(label) },
                    )
                }
            }

            if (tab == 0) RunsTab(runs, viewModel) else StructuresTab(state.structures, state.isLoadingStructures)
        }
    }
}

@Composable
private fun DashboardStrip(dashboard: PayrollDashboardDto) {
    AppCard(Modifier.fillMaxWidth().padding(12.dp)) {
        Row(Modifier.padding(14.dp)) {
            Figure("Paid", Formatters.currency(dashboard.totalPaid), Modifier.weight(1f))
            Figure("Pending", Formatters.currency(dashboard.totalPending), Modifier.weight(1f))
            Figure("Employees", Formatters.number(dashboard.employeeCount), Modifier.weight(1f))
        }
    }
}

@Composable
private fun Figure(label: String, value: String, modifier: Modifier = Modifier) {
    Column(modifier) {
        Text(value, style = MaterialTheme.typography.titleMedium)
        Text(
            label,
            style = MaterialTheme.typography.labelSmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
    }
}

@Composable
private fun RunsTab(runs: PagedListState<PayrollRunDto>, viewModel: PayrollViewModel) {
    when {
        runs.isInitialLoad -> FullScreenLoader()
        runs.error != null -> ErrorView(error = runs.error, onRetry = viewModel::refreshRuns)
        runs.isEmpty -> EmptyView(
            title = "No payroll runs",
            message = "Generate payroll for a month to see it here.",
        )

        else -> LazyColumn(
            contentPadding = androidx.compose.foundation.layout.PaddingValues(12.dp),
            verticalArrangement = Arrangement.spacedBy(8.dp),
        ) {
            items(runs.items.size, key = { runs.items[it].id }) { index ->
                val run = runs.items[index]
                EntityRowCard(
                    title = run.employeeName ?: "Employee #${run.employeeId}",
                    subtitle = "${Formatters.monthYear(run.month, run.year)} · " +
                        Formatters.humanizeEnum(run.employeeType),
                    metadata = "Basic ${Formatters.currency(run.basicSalary)} · " +
                        "deductions ${Formatters.currency(run.deductions + run.pf + run.esi)}",
                    leadingInitials = Formatters.initials(run.employeeName.orEmpty()),
                    trailing = {
                        Column(horizontalAlignment = Alignment.End) {
                            Text(
                                Formatters.currency(run.netSalary),
                                style = MaterialTheme.typography.titleSmall,
                            )
                            StatusChip(run.status)
                            Row {
                                TextButton(onClick = { viewModel.openSlip(run) }) { Text("Slip") }
                                if (run.status != "PAID") {
                                    TextButton(onClick = { viewModel.markPaid(run) }) { Text("Pay") }
                                }
                            }
                        }
                    },
                )
            }
            item { LoadMoreFooter(runs.isAppending, runs.appendError, viewModel::loadMoreRuns) }
        }
    }
}

@Composable
private fun StructuresTab(structures: List<SalaryStructureDto>, isLoading: Boolean) {
    when {
        isLoading -> FullScreenLoader()
        structures.isEmpty() -> EmptyView(title = "No salary structures")
        else -> LazyColumn(
            contentPadding = androidx.compose.foundation.layout.PaddingValues(12.dp),
            verticalArrangement = Arrangement.spacedBy(8.dp),
        ) {
            items(structures.size, key = { structures[it].id }) { index ->
                val structure = structures[index]
                EntityRowCard(
                    title = structure.employeeName ?: "Employee #${structure.employeeId}",
                    subtitle = Formatters.humanizeEnum(structure.employeeType),
                    metadata = "Basic ${Formatters.currency(structure.basicSalary)} · " +
                        "HRA ${Formatters.currency(structure.hra)} · " +
                        "DA ${Formatters.currency(structure.da)}",
                    leadingInitials = Formatters.initials(structure.employeeName.orEmpty()),
                    trailing = {
                        Text(
                            Formatters.currency(structure.grossSalary),
                            style = MaterialTheme.typography.titleSmall,
                        )
                    },
                )
            }
        }
    }
}

@HiltViewModel
class PayrollViewModel @Inject constructor(
    private val payrollRepository: PayrollRepository,
    private val documentOpener: DocumentOpener,
) : ViewModel() {

    private val _state = MutableStateFlow(PayrollUiState())
    val state: StateFlow<PayrollUiState> = _state.asStateFlow()

    private val runLoader = PagedLoader(viewModelScope) { page, size ->
        payrollRepository.getRuns(page = page, size = size)
    }
    val runs = runLoader.state

    init {
        runLoader.refresh()
        loadDashboard()
    }

    fun loadStructures() {
        if (_state.value.structures.isNotEmpty()) return
        _state.update { it.copy(isLoadingStructures = true) }
        viewModelScope.launch {
            _state.update {
                it.copy(
                    isLoadingStructures = false,
                    structures = payrollRepository.getSalaryStructures().getOrNull().orEmpty(),
                )
            }
        }
    }

    fun markPaid(run: PayrollRunDto) {
        viewModelScope.launch {
            val result = payrollRepository.markPaid(run.id, Formatters.apiDate(LocalDate.now()))
            when (result) {
                is ApiResult.Success -> {
                    runLoader.replaceWhere({ it.id == run.id }, result.data)
                    _state.update { it.copy(message = UiMessage.success("Marked as paid.")) }
                    loadDashboard()
                }

                is ApiResult.Failure -> _state.update { it.copy(message = UiMessage.error(result.error)) }
            }
        }
    }

    fun openSlip(run: PayrollRunDto) {
        viewModelScope.launch {
            when (val result = payrollRepository.downloadSalarySlip(run.id)) {
                is ApiResult.Success -> {
                    val opened = documentOpener.open(result.data)
                    if (!opened) {
                        _state.update {
                            it.copy(
                                message = UiMessage(
                                    "No app on this device can open a PDF.",
                                    isError = true,
                                ),
                            )
                        }
                    }
                }

                is ApiResult.Failure -> _state.update { it.copy(message = UiMessage.error(result.error)) }
            }
        }
    }

    private fun loadDashboard() {
        val today = LocalDate.now()
        viewModelScope.launch {
            _state.update {
                it.copy(
                    dashboard = payrollRepository.getDashboard(today.monthValue, today.year).getOrNull(),
                )
            }
        }
    }

    fun refreshRuns() = runLoader.refresh()
    fun loadMoreRuns() = runLoader.loadMore()
    fun consumeMessage() = _state.update { it.copy(message = null) }
}

data class PayrollUiState(
    val dashboard: PayrollDashboardDto? = null,
    val structures: List<SalaryStructureDto> = emptyList(),
    val isLoadingStructures: Boolean = false,
    val message: UiMessage? = null,
)
